### ISSUE TITLE
OCPP Not working or i don't understand it.

### ISSUE THREAD

**Issue by mennovanhout** [lbbrhzn/ocpp#134]
Hi there,

Maybe we can add some documentation about what sensors do.
When I connect my wallbox to OCPP it goes into lock mode and enable the bool unlock doesn't do much. I have to turn of availability:

![image](https://user-images.githubusercontent.com/26040589/131849593-502ca27b-476a-41b1-9cae-78013f0d9c81.png)

It's all prety unclear what switch does what. I also can't figure out how to pause charging and when i play to much with it my wallbox gets confused and bugged.

**Comment by lbbrhzn** [comment]
In order to start charging, the charger needs to be available, unlocked, and a transaction needs to be started.

The switches can be used for this:

charger.Availability will send an ChangeAvailability request. It will also cancel any ongoing transaction.
charger.Unlock will send an UnlockConnector request. It is only needed when the charger is locked.
charger.Charge_Control will send a RemoteStartTransaction request. Some chargers will automatically start a transaction when a you connect your charger to an EV, some will not.  In this case you need a RemoteStartTransaction to get things going.

Hope this helps. I agree it is a bit of a mess, and it would be nice if things are done automatically if needed.
