### ISSUE TITLE
Make Home Assistant notifications configurable by log level

### ISSUE THREAD

**Issue by N3rdix** [lbbrhzn/ocpp#272]
Some of the HA notifications and warnings are not important and useless. 
**Example**:
```
Charger Garage booted
```

<img width="491" alt="image" src="https://user-images.githubusercontent.com/70015952/147673569-2a6140bb-24cc-4cdb-a4ea-a7b21edc1309.png">

**Describe the solution you'd like**
Introduce some kind of log level within the integration to filter the notifications, e.g. debug, info, warning, error, fatal

**Comment by drc38** [comment]
By way of background to the notifications, there are 3 types:
 - Warnings thrown by the charger in response to a request from the integration (usually due to a feature not supported by the manufacturer)
 - Booting of charger (to confirm the charger has booted when pressing reset, or if there is some other reason that is useful to know about eg power failure/resore)
 - Data transfer from the charger which is unsolicited and will vary by charger as to when and why a transfer is sent

**Comment by drc38** [comment]
See #221 for how to setup the integration so it doesn't throw a MeterValuesSampledData warning.
